FROM node:16-bullseye

# Also exposing VSCode debug ports
EXPOSE 8000 9929 9230

RUN \
  apk upgrade && \
  apk add --no-cache python3 make g++ && \
  apk add vips-dev fftw-dev build-base \
    --update-cache \
    --repository http://dl-3.alpinelinux.org/alpine/edge/community \
    --repository http://dl-3.alpinelinux.org/alpine/edge/main \
  && rm -fR /var/cache/apk/*

RUN apk add automake autoconf libtool nasm

RUN npm install -g gatsby-cli

WORKDIR /app
COPY ./package.json .
RUN yarn install && yarn cache clean
COPY . .

# RUN chown -R node /app/node_modules
# USER node
RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache

CMD ["yarn", "develop", "-H", "0.0.0.0" ]